name = "SumOfSquares"
uuid = "4b9e565b-77fc-50a5-a571-1244f986bda1"
repo = "https://github.com/jump-dev/SumOfSquares.jl.git"
version = "0.4.3"

[deps]
ComplexOptInterface = "25c3070e-1275-41b5-afef-2f982c87090a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariateBases = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
PolyJuMP = "ddf597a6-d67e-5340-b84c-e37d84115374"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ComplexOptInterface = "0.0.2"
DynamicPolynomials = "0.3.6"
JuMP = "0.21"
MathOptInterface = "0.9.18"
MultivariateBases = "0.1.2"
MultivariateMoments = "0.3"
MultivariatePolynomials = "~0.3.5"
MutableArithmetics = "0.2"
PolyJuMP = "0.4.0"
Reexport = "0.2"
SemialgebraicSets = "0.2"
julia = "1"

[extras]
CSDP = "0a46da34-8e4b-519e-b418-48813639ff34"
Cyclotomics = "da8f5974-afbb-4dc8-91d8-516d5257c83b"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PermutationGroups = "8bc5a954-2dfc-11e9-10e6-cd969bffa420"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PolyJuMP = "ddf597a6-d67e-5340-b84c-e37d84115374"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "SCS", "LinearAlgebra", "DynamicPolynomials", "SparseArrays", "PolyJuMP", "Test", "CSDP"]
