name = "SumOfSquares"
uuid = "4b9e565b-77fc-50a5-a571-1244f986bda1"
repo = "https://github.com/jump-dev/SumOfSquares.jl.git"
version = "0.6.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariateBases = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
PolyJuMP = "ddf597a6-d67e-5340-b84c-e37d84115374"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymbolicWedderburn = "858aa9a9-4c7c-4c62-b466-2421203962a2"

[compat]
Combinatorics = "1"
DataStructures = "0.18"
JuMP = "1.5"
MathOptInterface = "1.13"
MultivariateBases = "0.1.2"
MultivariateMoments = "0.3"
MultivariatePolynomials = "0.4"
MutableArithmetics = "1"
PolyJuMP = "0.6"
Reexport = "0.2, 1.0"
SemialgebraicSets = "0.3"
SymbolicWedderburn = "0.3"
julia = "1.6"
