[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
